function parameters = loadFileByNameParameters()

parameters.Image = {...
           %%both soil and root in image
             '.\dataset\Rhizotron Scanner Images\FRMI Rhizotron Scans\FRMI 2017 Scans\8-9-17\DOE.S300_T312_L3_09.08.17_115803_1_FRMI.png',...
             '.\dataset\Rhizotron Scanner Images\FRMI Rhizotron Scans\FRMI 2017 Scans\5-22-17\DOE.S300_T111_L4_22.05.17_124057_1_FRMI.png',... 
           };% the full file path of image used to add training data from

       
parameters.ImageNumber = length(parameters.Image);% total number of image will be used to add training data from
parameters.replace_org = '.\dataset'; % the root path of original image


parameters.savefolder = struct(...
                         'savepath_pre','.\dataset\2017_07_07_PreprocessingResults',...% the root of preprocessing result                                                
                         'savepath_prePNG','.\dataset\2017_07_07_PreprocessingResults_png',...% the root of preprocessing result in png format                         
                         'savepath_seg','.\dataset\2017_07_07_SuperpixelSegmentationResults',...% the root of superpixel result
                         'savepath_fe','.\dataset\2017_07_07_FeatureExtractionResults',...% the root of feautre extraction result
                         'savepath_truth','.\dataset\2017_07_07_GroundTruth',...
                         'savepath_Miace','.\dataset\2017_07_07_MIACEResults',...
                         'savepath_MiacePNG','.\dataset\2017_07_07_MIACEResults_PNG',...    
                         'savepath_supbig','.\dataset\superbig',...
                         'savepath_insInBag','.\dataset\insInBag'...
                     ...
                         );
                     
parameters.savefile = struct(...                         
                         'tail_pre','_pre.mat',...         % the postfix filename of preprocessing result                                                 
                         'tail_prePNG','_pre.png',...      % the postfix filename of preprocessing result in png format                                             
                         'tail_seg','_sg.mat',...          % the postfix filename of superpixel result                   
                         'tail_fe','_fe.mat',...           % the postfix filename of feautre extraction result                      
                         'tail_truth','_BW2.mat',...                         
                         'tail_Miace','_miace.mat',...
                         'tail_MiacePNG','_miace.png',...
                         'tail_supbig','_supbig.mat',...
                         'tail_insInBag','_insInBag.mat'...
                     ...
                         );

parameters.loadfile = struct(...                                                              
                         'preFileName','preFileName',...           % absolute path of preprocessing result file                       
                         'pre_pngFileName','pre_pngFileName',...   % absolute path of preprocessing result file in png format     
                         'segFileName','segFileName',...           % absolute path of superpixel result file    
                         'feFileName','feFileName',...             % absolute path of feautre extraction result file          
                         'bwFileName','bwFileName',...
                         'miaceFileName','miaceFileName',...
                         'miacePngFileName','miacePngFileName',...
                         'bigsupFileName','bigsupFileName',...
                         'insInBagFileName','insInBagFileName'...
                     ...
                         ); 
                     
                     
                     
                     
                     